import { degToRad } from '../math/Units';
import type { AircraftConfig } from '../flight/AircraftConfig';

export const FIXED_DT = 1 / 120;

export const defaultAircraftConfig: AircraftConfig = {
  mass: 4200,
  wingArea: 22,
  wingSpan: 14.2,
  meanChord: 1.85,
  inertia: {
    ixx: 6200,
    iyy: 9800,
    izz: 14200,
  },
  aero: {
    CL0: 0.22,
    CLAlpha: 5.6,
    CLMaxAfterStall: 0.82,
    CLElevator: 0.5,
    CLFlap: 0.72,
    CD0: 0.026,
    inducedDragK: 0.04,
    CDFlap: 0.15,
    CDGear: 0.02,
    CDBrake: 0.08,
    CYBeta: -0.9,
    CYRudder: 0.22,
    CYp: -0.08,
    CYr: 0.18,
    Cm0: 0.015,
    CmAlpha: 0.82,
    CmElevator: -1.45,
    Cmq: -12,
    ClBeta: -0.08,
    ClAileron: 0.18,
    ClRudder: 0.035,
    Clp: -0.5,
    CnBeta: 0.12,
    CnRudder: -0.1,
    CnAileron: -0.035,
    Cnr: -0.2,
  },
  engine: {
    engineCount: 2,
    maxThrust: 9000,
    engineTimeConstant: 1.15,
    maxEffectiveAirspeed: 165,
    thrustLapseAtMaxSpeed: 0.58,
    idleRpm: 32,
    maxRpm: 101,
  },
  surfaces: {
    elevatorMaxRad: degToRad(28),
    aileronMaxRad: degToRad(20),
    rudderMaxRad: degToRad(30),
    flapMaxRad: degToRad(35),
    elevatorRateRadPerSec: degToRad(42),
    aileronRateRadPerSec: degToRad(58),
    rudderRateRadPerSec: degToRad(48),
    flapRateRadPerSec: degToRad(9),
    trimGainRad: degToRad(15),
  },
  stall: {
    alphaStallRad: degToRad(15),
    alphaFullStallRad: degToRad(25),
  },
  control: {
    keyboardPressRate: 0.56,
    keyboardReturnRate: 0.85,
    keyboardPitchLimit: 0.5,
    keyboardRollLimit: 0.62,
    keyboardYawLimit: 0.48,
    gamepadDeadzone: 0.08,
    gamepadExpo: 1.8,
    surfaceExpo: 1.35,
    highSpeedSensitivityStart: 70,
    highSpeedSensitivityEnd: 145,
    minHighSpeedSensitivity: 0.28,
    pitchDampingAssist: 0.58,
    pitchAttitudeAssist: 0.12,
    rollDampingAssist: 0.5,
    rollLevelAssist: 0.52,
    yawDamperAssist: 0.35,
    turnCoordinationAssist: 0.18,
    sideSlipAssist: 0.62,
  },
  autopilot: {
    engageAirspeed: 42,
    engageAltitude: 5,
    defaultClimbPitchRad: degToRad(4),
    minPitchRad: degToRad(-3),
    maxPitchRad: degToRad(7),
    maxRollRad: degToRad(22),
    waypointRadius: 120,
    headingKp: 1.1,
    pitchAdjustRateRadPerSec: degToRad(1.8),
    rollAdjustRateRadPerSec: degToRad(14),
    rollReturnRateRadPerSec: degToRad(8),
    pitchKp: 1.4,
    pitchKd: 1.2,
    rollKp: 1.55,
    rollKd: 1.1,
    maxPitchCommand: 0.35,
    maxRollCommand: 0.5,
  },
  ground: {
    wheelRadius: 0.36,
    springK: 90000,
    damperC: 9000,
    rollingFriction: 0.018,
    brakeFriction: 0.62,
    sideFriction: 9.5,
    crashVerticalSpeed: 5.5,
  },
  environment: {
    windX: 0,
    windY: 0,
    windZ: 0,
  },
};
